# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(0, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0,
                                      QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.carcontrolbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.carcontrolbutton.setFont(font)
        self.carcontrolbutton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
                                            "background-color: rgb(0, 0, 127);")
        self.carcontrolbutton.setObjectName("carcontrolbutton")
        self.verticalLayout.addWidget(self.carcontrolbutton)
        self.liveCamButton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setItalic(True)
        self.liveCamButton.setFont(font)
        self.liveCamButton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
                                         "background-color: rgb(0, 0, 127);")
        self.liveCamButton.setObjectName("liveCamButton")
        self.verticalLayout.addWidget(self.liveCamButton)
        self.videoStitchButton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setItalic(True)
        self.videoStitchButton.setFont(font)
        self.videoStitchButton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
                                             "background-color: rgb(0, 0, 127);")
        self.videoStitchButton.setObjectName("videoStitchButton")
        self.verticalLayout.addWidget(self.videoStitchButton)
        self.stereoVisionButton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setItalic(True)
        self.stereoVisionButton.setFont(font)
        self.stereoVisionButton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
                                              "background-color: rgb(0, 0, 127);")
        self.stereoVisionButton.setObjectName("stereoVisionButton")
        self.verticalLayout.addWidget(self.stereoVisionButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Please Choose a feature you want!"))
        self.carcontrolbutton.setText(_translate("MainWindow", "Car Control"))
        self.liveCamButton.setText(_translate("MainWindow", "Live Camera Feed"))
        self.videoStitchButton.setText(_translate("MainWindow", "Computer Vision: Video Stitching"))
        self.stereoVisionButton.setText(_translate("MainWindow", "Computer Vision: Stereo Vision"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
