# Form implementation generated from reading ui file 'manualControl.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ManualControl(object):
    def setupUi(self, ManualControl):
        ManualControl.setObjectName("ManualControl")
        ManualControl.resize(1103, 580)
        self.centralwidget = QtWidgets.QWidget(parent=ManualControl)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.title = QtWidgets.QWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAutoFillBackground(True)
        self.title.setStyleSheet("")
        self.title.setObjectName("title")
        self.frame = QtWidgets.QFrame(parent=self.title)
        self.frame.setGeometry(QtCore.QRect(0, 20, 1091, 80))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"selection-background-color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(480, 30, 161, 20))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 12pt \"8514oem\";\n"
"text-decoration: underline;\n"
"color: rgb(0, 255, 255);")
        self.label.setObjectName("label")
        self.highSpeed = QtWidgets.QRadioButton(parent=self.title)
        self.highSpeed.setGeometry(QtCore.QRect(900, 440, 95, 20))
        self.highSpeed.setMinimumSize(QtCore.QSize(12, 12))
        self.highSpeed.setSizeIncrement(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.highSpeed.setFont(font)
        self.highSpeed.setObjectName("highSpeed")
        self.mediumSpeed = QtWidgets.QRadioButton(parent=self.title)
        self.mediumSpeed.setGeometry(QtCore.QRect(900, 380, 131, 20))
        self.mediumSpeed.setMinimumSize(QtCore.QSize(12, 12))
        self.mediumSpeed.setSizeIncrement(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mediumSpeed.setFont(font)
        self.mediumSpeed.setObjectName("mediumSpeed")
        self.lowSpeed = QtWidgets.QRadioButton(parent=self.title)
        self.lowSpeed.setGeometry(QtCore.QRect(900, 320, 131, 20))
        self.lowSpeed.setMinimumSize(QtCore.QSize(12, 12))
        self.lowSpeed.setSizeIncrement(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lowSpeed.setFont(font)
        self.lowSpeed.setObjectName("lowSpeed")
        self.label_2 = QtWidgets.QLabel(parent=self.title)
        self.label_2.setGeometry(QtCore.QRect(920, 240, 55, 31))
        self.label_2.setStyleSheet("font: 8pt \"Pristina\";\n"
"font: 75 8pt \"8514oem\";\n"
"font: 75 8pt \"8514oem\";\n"
"text-decoration: underline;\n"
"font: 16pt \"Pristina\";\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"Pristina\";\n"
"font: 16pt \"Pristina\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.title)
        self.label_3.setGeometry(QtCore.QRect(340, 200, 391, 20))
        self.label_3.setStyleSheet("font: 75 italic 12pt \"8514oem\";\n"
"font: 75 8pt \"8514oem\";")
        self.label_3.setObjectName("label_3")
        self.frontButton = QtWidgets.QPushButton(parent=self.title)
        self.frontButton.setGeometry(QtCore.QRect(500, 240, 81, 71))
        self.frontButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("arrows/front arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.frontButton.setIcon(icon)
        self.frontButton.setIconSize(QtCore.QSize(60, 60))
        self.frontButton.setObjectName("frontButton")
        self.backButton = QtWidgets.QPushButton(parent=self.title)
        self.backButton.setGeometry(QtCore.QRect(500, 430, 81, 71))
        self.backButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("arrows/back arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.backButton.setIcon(icon1)
        self.backButton.setIconSize(QtCore.QSize(60, 60))
        self.backButton.setObjectName("backButton")
        self.rightButton = QtWidgets.QPushButton(parent=self.title)
        self.rightButton.setGeometry(QtCore.QRect(500, 330, 81, 31))
        self.rightButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("arrows/right arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rightButton.setIcon(icon2)
        self.rightButton.setIconSize(QtCore.QSize(60, 60))
        self.rightButton.setObjectName("rightButton")
        self.startButton = QtWidgets.QPushButton(parent=self.title)
        self.startButton.setGeometry(QtCore.QRect(30, 260, 181, 101))
        self.startButton.setStyleSheet("font: 16pt \"Pristina\";\n"
"font: 16pt \"Onyx\";\n"
"")
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(parent=self.title)
        self.stopButton.setGeometry(QtCore.QRect(30, 400, 181, 101))
        self.stopButton.setStyleSheet("font: 16pt \"Pristina\";\n"
"font: 16pt \"Onyx\";\n"
"")
        self.stopButton.setObjectName("stopButton")
        self.leftButton = QtWidgets.QPushButton(parent=self.title)
        self.leftButton.setGeometry(QtCore.QRect(500, 380, 81, 31))
        self.leftButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("arrows/left arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.leftButton.setIcon(icon3)
        self.leftButton.setIconSize(QtCore.QSize(60, 60))
        self.leftButton.setObjectName("leftButton")
        self.gridLayout.addWidget(self.title, 0, 1, 1, 1)
        ManualControl.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ManualControl)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 26))
        self.menubar.setObjectName("menubar")
        ManualControl.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ManualControl)
        self.statusbar.setObjectName("statusbar")
        ManualControl.setStatusBar(self.statusbar)

        self.retranslateUi(ManualControl)
        QtCore.QMetaObject.connectSlotsByName(ManualControl)

    def retranslateUi(self, ManualControl):
        _translate = QtCore.QCoreApplication.translate
        ManualControl.setWindowTitle(_translate("ManualControl", "MainWindow"))
        self.label.setText(_translate("ManualControl", "Manual Control"))
        self.highSpeed.setText(_translate("ManualControl", "High"))
        self.mediumSpeed.setText(_translate("ManualControl", "Medium"))
        self.lowSpeed.setText(_translate("ManualControl", "low"))
        self.label_2.setText(_translate("ManualControl", "Speed"))
        self.label_3.setText(_translate("ManualControl", "Choose how do you want the car to move:"))
        self.startButton.setText(_translate("ManualControl", "Start"))
        self.stopButton.setText(_translate("ManualControl", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManualControl = QtWidgets.QMainWindow()
    ui = Ui_ManualControl()
    ui.setupUi(ManualControl)
    ManualControl.show()
    sys.exit(app.exec())
